# Generated by Django 6.0.5 on 2026-05-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_pessoal_options_remove_pessoal_imagem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoal",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="imagens/"),
        ),
    ]
