# Generated by Django 6.0.5 on 2026-05-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_pessoal_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoal",
            name="subtitulo",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
