"""
Django settings for portfolio_pessoal project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-7@t+j-(d!v!&v0kk+l7nv5&m=h!n6z-1^0ferd#*x46+)v=&d*"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "portfolio",
    "rest_framework",
    "tarefas"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "portfolio_pessoal.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.notificacao_ms',
            ],
        },
    },
]

WSGI_APPLICATION = "portfolio_pessoal.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
MEDIA_URL = '/media/' #ao acessar a url, será mostrada arquivos da pasta media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ─── Configuracoes do Django REST Framework ───

REST_FRAMEWORK  =  {

# Define que, por padrao, todas as views exigem autenticacao

'DEFAULT_AUTHENTICATION_CLASSES':  [

'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT (principal)

'rest_framework.authentication.SessionAuthentication',  # Sessao (para API navegavel)

],

# Define que, por padrao, apenas usuarios autenticados podem acessar

'DEFAULT_PERMISSION_CLASSES':  [

'rest_framework.permissions.IsAuthenticated',

],

}

  

# ─── Configuracoes do SimpleJWT ───

from datetime import timedelta

  

SIMPLE_JWT  =  {

'ACCESS_TOKEN_LIFETIME':  timedelta(minutes=30),  # Token de acesso vale 30 minutos

'REFRESH_TOKEN_LIFETIME':  timedelta(days=1),  # Token de refresh vale 1 dia

}

# ─── Microserviço de Notificação ───
NOTIFICACAO_MS_URL = 'http://127.0.0.1:8001'
NOTIFICACAO_MS_API_KEY = '335519b61002e7f2'
